name: Run tests and lint

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio flake8 black
        
        

    - name: Run pytest
      run: pytest -v

    - name: Run isort
      run: isort --check-only --diff .

    - name: Run black (format check)
      run: black --check --diff .

    - name: Run flake8 (linting)
      run: flake8 .


